/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AnalyticsRouteImport } from "./routes/analytics";
import { Route as ApplicationsRouteImport } from "./routes/applications";
import { Route as CalendarRouteImport } from "./routes/calendar";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ApplicationsIndexRouteImport } from "./routes/applications.index";
import { Route as ApplicationsIdRouteImport } from "./routes/applications.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: "/applications",
  path: "/applications",
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarRoute = CalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ApplicationsRoute,
} as any);
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApplicationsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/applications": typeof ApplicationsRouteWithChildren;
  "/calendar": typeof CalendarRoute;
  "/settings": typeof SettingsRoute;
  "/applications/$id": typeof ApplicationsIdRoute;
  "/applications/": typeof ApplicationsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/calendar": typeof CalendarRoute;
  "/settings": typeof SettingsRoute;
  "/applications/$id": typeof ApplicationsIdRoute;
  "/applications": typeof ApplicationsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/applications": typeof ApplicationsRouteWithChildren;
  "/calendar": typeof CalendarRoute;
  "/settings": typeof SettingsRoute;
  "/applications/$id": typeof ApplicationsIdRoute;
  "/applications/": typeof ApplicationsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/analytics"
    | "/applications"
    | "/calendar"
    | "/settings"
    | "/applications/$id"
    | "/applications/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/analytics"
    | "/calendar"
    | "/settings"
    | "/applications/$id"
    | "/applications";
  id:
    | "__root__"
    | "/"
    | "/analytics"
    | "/applications"
    | "/calendar"
    | "/settings"
    | "/applications/$id"
    | "/applications/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AnalyticsRoute: typeof AnalyticsRoute;
  ApplicationsRoute: typeof ApplicationsRouteWithChildren;
  CalendarRoute: typeof CalendarRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/analytics": {
      id: "/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applications": {
      id: "/applications";
      path: "/applications";
      fullPath: "/applications";
      preLoaderRoute: typeof ApplicationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calendar": {
      id: "/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof CalendarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applications/": {
      id: "/applications/";
      path: "/";
      fullPath: "/applications/";
      preLoaderRoute: typeof ApplicationsIndexRouteImport;
      parentRoute: typeof ApplicationsRoute;
    };
    "/applications/$id": {
      id: "/applications/$id";
      path: "/$id";
      fullPath: "/applications/$id";
      preLoaderRoute: typeof ApplicationsIdRouteImport;
      parentRoute: typeof ApplicationsRoute;
    };
  }
}

interface ApplicationsRouteChildren {
  ApplicationsIdRoute: typeof ApplicationsIdRoute;
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute;
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsIdRoute: ApplicationsIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
};

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
